

services:
  calculator:
    build:
      context: ./calculator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  deal:
    build:
      context: ./deal
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - database

  statement:
    build:
      context: ./statement
      dockerfile: Dockerfile
    ports:
      - "8100:8080"
    depends_on:
      - database

  dossier:
    build:
      context: ./dossier
      dockerfile: Dockerfile
    ports:
      - "8110:8080"
    depends_on:
      - database

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8120:8080"
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

volumes:
  postgres-data:




